// Counter actions
const COUNTER_INCREASE='@COUNTER/INCREASE'
const COUNTER_DECREASE='@COUNTER/DECREASE'
const COUNTER_RESET='@COUNTER/RESET'

// Message Actions 
const MESSAGE_CREATE_NEW = '@COUNTER/CREATE_NEW'
const MESSAGE_DELETE = '@COUNTER/DELETE'
const MESSAGE_UPDATE = '@COUNTER/UPDATE'

// User Actions --> Public facing info about a user.
const USER_LOGIN = '@USER/LOGIN'
const USER_lOGOUT = '@USER/lOGOUT'
const USER_GET_PROFILE = '@USER/GET_PROFILE'  
const USER_UPDATE_PROFILE = '@USER/UPDATE_PROFILE'

// Account actions --> More private/account management type actions
const ACCOUNT_CREATE = '@USER/CREATE'
const ACCOUNT_REMOVE_ACCOUNT_CANNOT_UNDO_GDPR_RIGHT_TO_BE_FORGOTTEN = '@USER/REMOVE_ACCOUNT_CANNOT_UNDO_GDPR_RIGHT_TO_BE_FORGOTTEN'
const ACCOUNT_GET_ACOUNT_INFO = '@USER/GET_PROFILE' // This is a duplicate our script should catch 
const ACCOUNT_UPDATE_ACCOUNT_INFO = '@USER/UPDATE_PROFILE'